
FAIL Calling respondWith asynchronously throws an exception promise_test: Unhandled rejection with value: object "Error: wait_for_state must be passed a ServiceWorker"

