
FAIL Fetch event handler throws after a successful respondWith() promise_test: Unhandled rejection with value: object "Error: wait_for_state must be passed a ServiceWorker"

