
FAIL XMLHttpRequest: members during network errors (sync) assert_throws: send function "function () { client.send(null) }" threw object "Error: NETWORK_ERR: XMLHttpRequest Exception 101" that is not a DOMException NetworkError: property "code" is equal to 101, expected 19

